In [155]:
def min_hours(arr, p, i):
    import numpy as np
    arr = np.array(sorted(arr))
    diff = arr - arr.reshape(-1, 1)
    positive_diff = np.where(diff<0, 0, diff)
    solution = min(np.sum(positive_diff, axis=0)[p-1:])
    
    return f"Case #{i}: {solution}"

In [135]:
test_cases = int(input())

for i in range(test_cases):
    
    np = input().split()
    n, p = int(np[0]), int(np[1])

    arr = list(map(int, input().rstrip().split()))
    
    print(min_hours(arr, p, i+1))
    

3
4 3
5 1 9 100
Case #1: 12
5 5
7 7 1 7 7
Case #2: 6
6 2
5 5 1 2 3 4
Case #3: 0


In [156]:
min_hours([2, 2, 6, 5, 4, 7, 20], 5, 0)

'Case #0: 11'

In [149]:
a = [2, 2, 6, 5, 4, 7, 20, 1, 2]

In [145]:
a.sort()

In [154]:
a

[2, 2, 6, 5, 4, 7, 20, 1, 2]

In [157]:
sorted(a)

[1, 2, 2, 2, 4, 5, 6, 7, 20]

In [166]:
import numpy as np
aa = np.array([a, a])

In [168]:
aa

array([[ 2,  2,  6,  5,  4,  7, 20,  1,  2],
       [ 2,  2,  6,  5,  4,  7, 20,  1,  2]])

In [171]:
bb = np.random.rand(aa.shape[0], aa.shape[1])
bb

array([[0.0780017 , 0.72632627, 0.85809022, 0.19405732, 0.41407623,
        0.64498882, 0.25408059, 0.94408642, 0.70314987],
       [0.16298944, 0.30025701, 0.28965404, 0.38302879, 0.21337004,
        0.51646128, 0.71126271, 0.01973589, 0.09924521]])

In [176]:
np.divide(np.multiply(aa,(bb > 0.5)), 0.5)

array([[ 0.,  4., 12.,  0.,  0., 14.,  0.,  2.,  4.],
       [ 0.,  0.,  0.,  0.,  0., 14., 40.,  0.,  0.]])