In [2]:
import numpy as np

In [3]:
p = np.array([9, 11, 8, 5, 7, 10])
q = p.reshape(-1, 1)

In [4]:
profit = q - p

In [5]:
profit

array([[ 0, -2,  1,  4,  2, -1],
       [ 2,  0,  3,  6,  4,  1],
       [-1, -3,  0,  3,  1, -2],
       [-4, -6, -3,  0, -2, -5],
       [-2, -4, -1,  2,  0, -3],
       [ 1, -1,  2,  5,  3,  0]])

X  9 11 8 5 7 10
9  x x  x x x x
11 x x  x x x x
8  x x  x x x x
5  x x  x x x x
7  x x  x x x x
10 x x  x x x x

In [9]:
m = 0
for i in range(6):
    n = (profit[i, 0:i+1])
    m = max(n) if m < max(n) else m        
    print(max(n), n)

0 [0]
2 [2 0]
0 [-1 -3  0]
0 [-4 -6 -3  0]
2 [-2 -4 -1  2  0]
5 [ 1 -1  2  5  3  0]


In [20]:
np.where(profit<0, 0, profit)

array([[0, 0, 1, 4, 2, 0],
       [2, 0, 3, 6, 4, 1],
       [0, 0, 0, 3, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [1, 0, 2, 5, 3, 0]])

In [21]:
profit[0]

array([ 0, -2,  1,  4,  2, -1])